### PR TITLE
Refactored OLS method

### PR DESCRIPTION
**Pull request by ejolly**
@ljchang I can't get your SRM tests to pass locally, not sure how you did that. Also I think we should use tox to easily test on python 2 and 3. I can't get your tests to even run on my py3.6 environment.

### CODE REVIEW

**Comment by ljchang** [comment]
@ejolly.  I added tox, but can't get it to work right with conda on my system.  Not sure why your tests aren't passing.  they work on my system and travis.  Want to give more specific error messages?

**Comment by ljchang** [comment]
It looks like your srm tests are failing with the different MNI template.  The number of voxels changes, which screws up the number of features used in the tests.

**Comment by ejolly** [comment]
@ljchang Since you wrote the SRM tests can you edit the number of features as required for the 3mm template (there are fewer voxels)?

As I noted, on [this previous commit](https://github.com/ljchang/nltools/commit/ea74b5cd2ae93ad62bd3a00131d6f7a959e7abe6#diff-a38dd933e0bb574e2a47e6d547da7848) you made a change that resulted in never actually testing *both* the 3mm and 2mm templates. The tests in this PR now loop over both template sizes to fix that, which is why your local SRM tests never caught this issue.

**Comment by ljchang** [comment]
I removed the 3mm tests because I think we should add that as the input into the test module.  I put that code there as a placeholder to remind us of what the values are.  It take way too long to test everything for both 2mm and 3mm at the moment.

**Comment by ejolly** [comment]
Ok maybe we should figure out what tests we don't want/need to duplicate and which ones are critical because the output might change due to a bug we don't notice.

**Pull request merged**
