### PR TITLE
Fix perm tail

### PR DESCRIPTION
**Pull request by jcheong0428**
changed permutation testing default to two tailed 
added tests.

### CODE REVIEW

**Comment by jcheong0428** [comment]
@ljchang @ejolly Any idea what might be causing this to fail? 
Seems to be crashing while importing nilearn functions 
```from nilearn.plotting import plot_glass_brain, plot_stat_map```
However test is passing on my computer for both python 2 and 3.

**Comment by ejolly** [comment]
Hmm that's weird. Not totally sure. Is this thread helpful: https://github.com/nilearn/nilearn/issues/1235 ? Look like it might be a sklearn problem. We could try updating our scikit learn requirement to 0.19.1.

**Comment by ljchang** [comment]
Here is the error message:

```
_________________ ERROR collecting nltools/tests/test_data.py __________________
nltools/tests/test_data.py:6: in <module>
    from nltools.simulator import Simulator
nltools/__init__.py:17: in <module>
    from .analysis import Roc
nltools/analysis.py:16: in <module>
    from nltools.plotting import roc_plot
nltools/plotting.py:28: in <module>
    from nilearn.plotting import plot_glass_brain, plot_stat_map
../../../miniconda/envs/testenv/lib/python3.6/site-packages/nilearn/plotting/__init__.py:41: in <module>
    from .img_plotting import plot_img, plot_anat, plot_epi, \
../../../miniconda/envs/testenv/lib/python3.6/site-packages/nilearn/plotting/img_plotting.py:511: in <module>
    cmap=plt.cm.spectral, vmin=None, vmax=None, **kwargs):
E   AttributeError: module 'matplotlib.cm' has no attribute 'spectral'
```

Doubt it has anything to do with sklearn.  Maybe update matplotlib. Nilearn is up to date.

**Comment by jcheong0428** [comment]
Tried rerunning @ejolly 's previous pull request which passed the test before but it's failing now. 
Might be something weird happening with Travis CI

**Comment by ljchang** [comment]
yeah, this is super weird.  Maybe there is a cache that needs to be reset?

**Comment by ljchang** [comment]
It doesn't look we are using caches, but this might help speed up tests if we cached conda build.  https://docs.travis-ci.com/user/caching/

**Comment by ljchang** [comment]
@jcheong0428 @ejolly:  I figured out the bug.  It was an issue with the pypi version of nilearn not having an updated import for the newer versions of matplotlib see https://github.com/nilearn/nilearn/issues/1618.   

I added a super janky temporary fix for this, where we just override the pypi nilearn version with the current github version everytime we run tests.  We should fix this at some point.

**Pull request merged**
